export const sortofarttype = [
  "Non spécifié / autre",
  "Peinture",
  "Sculpture",
  "Dessin",
  "Gravure",
  "Photographie",
  "Art numérique",
  "Art textile",
  "Céramique",
  "Artisanat",
  "Art mural",
  "Art vidéo",
  "Performance artistique",
  "Installation artistique",
  "Art cinétique",
  "Art environnemental",
  "Art sonore",
]
