export const sortofcourant = [
  "Non spécifié / autre",
  "Art contemporain",
  "Art moderne",
  "Art abstrait",
  "Art figuratif",
  "Art impressionniste",
  "Art expressionniste",
  "Art cubiste",
  "Art surréaliste",
  "Art réaliste",
  "Art minimaliste",
  "Art conceptuel",
  "Art pop",
  "Art postmoderne",
  "Art romantique",
  "Art baroque",
  "Art rococo",
]
